### PR TITLE
bugfix not pass protocols parameter to WebSocket

### PR DESCRIPTION
**Pull request by chungheepark**
#34 implement

### CODE REVIEW

**Comment by artrmz** [comment]
Anything wrong with this PR? It's been waiting for a review/merge for quite some time.

**Comment by kevmoo** [comment]
@artrmz A test would be nice, along with an update to the version and the changelog

**Comment by artrmz** [comment]
@chungheepark Still interested in merging this PR? Let me know if you want to update the version and the changelog. If not I think I'll just open another PR.

**Comment by banalg** [comment]
Hello, when do you plan to merge this PR ?

I had the same issue and manually updated the code in my .pub-cache file as done in this PR (juste added the protocols). This solved my issue.

Nota : I had this issue when trying to call the websocket API of the Janus webRTC gateway. As @chungheepark in the issue #34. It seems very few applications make the protocol mandatory, that's probably why we are only two requesting this PR.

**Comment by chungheepark** [comment]
@artrmz What can I do?

**Comment by artrmz** [comment]
@chungheepark As kevmoo suggested, need to add test for that and update a changelog + bump up the version ^^

**Comment by chungheepark** [comment]
@artrmz Okay! I will! : )

**Comment by chungheepark** [comment]
@artrmz I can't find previous workspace.. So close and re-open PR.

**Pull request closed without merging**
