### PR TITLE
Add HtmlWebSocketChannel.innerWebSocket

### PR DESCRIPTION
**Pull request by chirag729**
Add HtmlWebSocketChannel.innerWebSocket to match IOWebSocketChannel.innerWebSocket

### CODE REVIEW

**Comment by amitrotner** [comment]
Can someone please merge this?

**Comment by gustav3d** [comment]
Any progress ?

**Comment by chirag729** [comment]
@kevmoo Is anyone available to review pull requests for this repo?

**Comment by kevmoo** [comment]
@natebosch @devoncarew ?

**Comment by natebosch** [comment]
Thanks for the PR!

Since the field is public we can expose it directly (it doesn't have a setter that shouldn't be in the API like was the case for `IOWebSocketChannel`).

This also allows it to be non-nullable, due to the differences between the way we connect websockets on the web and VM.

**Comment by natebosch** [comment]
@kevmoo - since I changed this can you also do a review?

**Comment by kevmoo** [comment]
Any concerns about exposing implementation details?

**Comment by natebosch** [comment]
> Should we drop the `-dev` and just ship?

Sure I can skip the extra PR. We'll still need to sync the package before publish.

**Comment by chirag729** [comment]
@natebosch - Any chance an update could be published?

**Comment by natebosch** [comment]
We had some blockers with package rolls, but it looks like this has rolled though so I went ahead and published.

**Pull request merged**
