### PR TITLE
Updates for Dart 2.0 corelib changes (wave 2.2).

### PR DESCRIPTION
**Pull request by leafpetersen**
Changes code that `implements StreamTransformer` to `extend StreamTransformerBase`.

### CODE REVIEW

**Comment by leafpetersen** [comment]
The changes to websocket haven't changed yet.  How about I leave this version sitting in a branch so that we can use it internally and in the SDK, and then once the changes land in the SDK we can abandon this and you can publish a new version using your process?

**Comment by nex3** [comment]
Sounds fine.

**Comment by nex3** [comment]
This was fixed by 0f37053c95b3c27e5b985c194bb42a818074e6af.

**Comment by leafpetersen** [comment]
Restoring branch temporarily until I roll SDK deps.

**Comment by nex3** [comment]
Oops, sorry about that!

**Comment by leafpetersen** [comment]
No problem, I didn't know this was an issue until it came up with async, and I meant to fix this up then, but didn't get around to it in time.  Just sent you a CL to roll deps, then we should be able to delete.

**Pull request closed without merging**
