### PR TITLE
add library names; increase the sdk constraint

### PR DESCRIPTION
**Pull request by devoncarew**
- add library names (fix the appearance in https://docs.flutter.io/)
- increase the sdk constraint to `<2.0.0-dev.infinity`

@nex3 @kevmoo 

(I think we'll want to publish this version after this lands; looks like only @nex3 is a publisher, which we'll probably want to expand a bit)

### CODE REVIEW

**Comment by kevmoo** [comment]
> (I think we'll want to publish this version after this lands; looks like only @nex3 is a publisher, which we'll probably want to expand a bit)

I have the master key 😄

**Comment by kevmoo** [comment]
@devoncarew – want me to publish?

**Comment by devoncarew** [comment]
👍

**Comment by nex3** [comment]
Why are we adding back library names? I thought we were well done with them.

**Pull request merged**
